name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.PA_HOST }}
          username: ${{ secrets.PA_USER }}
          key: ${{ secrets.PA_SSH_KEY }}
          script: |
            cd ~/mysite
            git pull origin main

            if [ -f requirements.txt ]; then
              source venv_portfolio/bin/activate
              pip install -r requirements.txt
            fi

            touch /var/www/www_vijayrodrigues_com_wsgi.py